[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"

[tool]
[tool.poetry]
name = "aws-adfs"
version = "1.21.1+1.gcb506f8"
description = "AWS Cli authenticator via ADFS - small command-line tool to authenticate via ADFS and assume chosen role"
keywords = ["aws", "adfs", "console", "tool"]
classifiers = ["Development Status :: 5 - Production/Stable", "Environment :: Console", "Intended Audience :: End Users/Desktop", "Intended Audience :: Developers", "Intended Audience :: System Administrators", "License :: OSI Approved :: Python Software Foundation License", "Operating System :: MacOS :: MacOS X", "Operating System :: Microsoft :: Windows", "Operating System :: POSIX", "Programming Language :: Python"]
authors = ["Venth <artur.krysiak.warszawa@gmail.com>", "Venth"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=2.7.6,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*"
botocore = ">=1.12.6"
click = "*"
configparser = "*"
coverage = {version = "<4", optional = true}
fido2 = ">=0.8.1,<0.9.0"
lxml = {version = "<4.4.0", python = ">=3.5"}
mock = {optional = true, version = "*"}
pytest = {optional = true, version = "*"}
pytest-runner = {optional = true, version = "*"}
requests = {extras = ["security"], version = "*"}
requests-kerberos = "*"

[tool.poetry.extras]
test = ["coverage", "mock", "pytest", "pytest-runner"]
